### PR TITLE
Fixed the old research registration

### LINKED ISSUE #15: Error on the newest SF version
```
[13:17:13] [Server thread/ERROR]: Error occurred while enabling SoundMuffler vDEV - 12 (git 7303b3a9) (Is it up to date?)
java.lang.NoSuchMethodError: 'void me.mrCookieSlime.Slimefun.api.Slimefun.registerResearch(me.mrCookieSlime.Slimefun.Objects.Research, org.bukkit.inventory.ItemStack[])'
	at dev.j3fftw.soundmuffler.SoundMuffler.onEnable(SoundMuffler.java:30) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-101]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-101]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-101]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-101]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-101]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

Plugin doesn't work
Minecraft Version: 1.16.1
CS-CoreLib Version: 88
Slimefun Version: 588
Plugin Version: 12

@J3fftw1

### PR DESCRIPTION
**Pull request by poma123**
## Description
Fixed the old research registration, and updated Slimefun dependency version to RC-15.

## Changes
same here

## Related issues
Fixes #15 

## Checklist stuff
* [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
* [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
* [x] I followed the existing code standards and didn't mess up the formatting.
* [x] Panda is lazy
* [ ] I did my best to add documentation to any public classes or methods I added.
* [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

File: src/main/java/dev/j3fftw/soundmuffler/SoundMuffler.java [hunk 1]
```diff
@@ -27,8 +26,9 @@ public void onEnable() {
         SoundMufflerMachine soundMufflerMachine = new SoundMufflerMachine();
         soundMufflerMachine.register(this);
 
-        Slimefun.registerResearch(new Research(new NamespacedKey(this, "sound_muffler"), 6912, "Sound Muffler", 11),
-            soundMufflerMachine.getItem());
+        Research research = new Research(new NamespacedKey(this, "sound_muffler"), 6912, "Sound Muffler", 11);
+        research.addItems(soundMufflerMachine.getItem());
+        research.register();
```
Comment (WalshyDev) [inline src/main/java/dev/j3fftw/soundmuffler/SoundMuffler.java]: Chain these and put them on new lines

**Review by WalshyDev — CHANGES_REQUESTED** [review]

File: src/main/java/dev/j3fftw/soundmuffler/SoundMuffler.java (hunk 1 above)
Comment (poma123) [reply src/main/java/dev/j3fftw/soundmuffler/SoundMuffler.java:32]: Like this?
